DROP TABLE IF EXISTS product;

CREATE TABLE product
(
    id        INT AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(255)   NOT NULL,
    price     DECIMAL(10, 2) NOT NULL,
    image_url VARCHAR(255)
);

ALTER TABLE product ALTER COLUMN id RESTART WITH 1;