### get product list
GET http://localhost:8080/api/wishes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImVtYWlsIiwibmlja25hbWUiOiJuaWNrbmFtZSIsImlhdCI6MTcyMDE2MTA3NCwiZXhwIjoxNzIwNTIxMDc0fQ.z97hNmK9URUHFGp8gJ3ckFr4uLsULWakshIaenxqyb9gIhrP8C1ohCp64qSAMlB4s2Kz3Kym0UF1z82otQphxA
Content-Type: application/json

### get product

### create product

### update product

### delete product